name: step summary
description: step summary
runs:
  using: composite
  steps:
    - shell: bash
      run: echo foo >> "$GITHUB_STEP_SUMMARY"
    - shell: bash
      run: echo bar >> "$GITHUB_STEP_SUMMARY"
