---
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@feat/add-for-fork
    if: "! github.event.pull_request.head.repo.fork"
    with:
      aqua_version: v1.32.3
      aqua_policy_config: aqua-policy.yaml
    permissions:
      pull-requests: write
      contents: read

  actionlint_fork:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint_fork.yaml@feat/add-for-fork
    if: github.event.pull_request.head.repo.fork
    with:
      aqua_version: v1.32.3
      aqua_policy_config: aqua-policy.yaml
    permissions: {}
