---
name: enable automerge
on:
  pull_request:
    branches: [master]
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: enable automerge
        run: gh pr merge -R "$GITHUB_REPOSITORY" --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
