---
name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: list-targets
  build:
    runs-on: ${{matrix.target.runs_on}}
    needs: setup
    strategy:
      matrix:
        target: ${{needs.setup.outputs.targets}}
    steps:
    - uses: actions/checkout@v2
    - run: echo ${{matrix.target.target}}
