---
name: test message
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo '::debug title=title_debug::debug'
    - run: echo '::notice title=title_notice::notice'
    - run: echo '::warning title=title_warning::warning'
    - run: echo '::error title=title_error::error'
