---
name: Notify release Creation
on:
  release:
    types:
      - unpublished
      - published
      # - released
      # - prereleased
      - edited
# created: A draft was saved, or a release or pre-release was published without previously being saved as a draft.
# deleted: A release, pre-release, or draft release was deleted.
# edited: The details of a release, pre-release, or draft release were edited. https://docs.github.com/repositories/releasing-projects-on-github/managing-releases-in-a-repository#editing-a-release
# prereleased: A release was created and identified as a pre-release. A pre-release is a release that is not ready for production and may be unstable.
# published: A release, pre-release, or draft of a release was published.
# released: A release was published, or a pre-release was changed to a release.
# unpublished: A release or pre-release was unpublished.
jobs:
  notify-release-creation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{ toJSON(github) }}
      - run: echo "$MESSAGE"
        env:
          MESSAGE: |
            repository: ${{ github.repository }}
            event: ${{ github.event_name }}
            action: ${{ github.event.action }}
            tag: ${{ github.event.release.tag_name }}
            html_url: ${{ github.event.release.html_url }}
      - uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: D3LG8NSNB
          # For posting a simple plain text message
          slack-message: |
            repository: ${{ github.repository }}
            event: ${{ github.event_name }}
            action: ${{ github.event.action }}
            tag: ${{ github.event.release.tag_name }}
            html_url: ${{ github.event.release.html_url }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
