---
name: Discussion
on:
  discussion:
    types:
      - created
      - labeled
      - answered
  discussion_comment:
    types:
      - created
permissions:
  # "permissions" section should not be empty
  contents: read
  discussions: read
  pages: read
  metadata: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
      - uses: actions/checkout@v3
      # read config
      # get labels
      # Send notification to slack
