name: push
on:
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: date > date.txt
    - run: git add date.txt
    - run: git commit -m "update date.txt"
    - run: git push origin master
