---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.25.0
      - run: tfcmt -v
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@main
        with:
          aqua_version: v1.25.0
      - run: tfcmt -v
