---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo foo >> "$GITHUB_STEP_SUMMARY"
      - run: echo bar >> "$GITHUB_STEP_SUMMARY"
