---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: windows-latest
    steps:
      - run: |
           echo "$HOME/AppData/Local/aquaproj-aqua/bin" >> $GITHUB_PATH
        shell: bash
      - run: |
           echo $PATH
        shell: bash
      - run: |
          echo $env:PATH
        shell: pwsh
    # - run: |
    #     echo "$HOME/AppData/Local/aquaproj-aqua/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    #   shell: pwsh
