---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.11.0-1
      - run: ls -lh ~/.local/share/aquaproj-aqua/bin
        shell: bash
      - run: "which ci-info || :"
        shell: bash
      - run: "aqua which ci-info || :"
        shell: bash
