---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: windows-latest
    steps:
      - run: |
           echo $GITHUB_PATH
        shell: bash
      - run: |
          echo $env:GITHUB_PATH
        shell: pwsh
