---
name: Test
on:
  pull_request:
    branches: [main]
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo foo >> "$GITHUB_STEP_SUMMARY"
      - shell: bash
        run: echo bar >> "$GITHUB_STEP_SUMMARY"
