---
name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.added_modified }}; do
          echo "${changed_file}"
        done
