---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "name=foo" >> "$GITHUB_OUTPUT"
        id: name
      - run: echo "$NAME"
        env:
          NAME: ${{steps.name.outputs.name}}
