---
name: Test
on:
  pull_request: {}
jobs:
  foo:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh -R aquaproj/example-update-checksum pr review -a "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{github.token}}
          PR_NUMBER: ${{github.event.number}}
