---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: ubuntu-latest
    if: "false"
    steps:
      - run: "true"
  zoo:
    runs-on: ubuntu-latest
    steps:
      - run: "true"
  bar:
    runs-on: ubuntu-latest
    needs:
      - foo
      - zoo
    steps:
      - run: "true"
